### ISSUE TITLE
Proposal to move py/ to public repo

### ISSUE THREAD

**Issue by b-bondurant** [quartiq/booster#241]
I understand that the firmware itself is strictly licensed and as such access to this repo must be restricted, but IMO the python files for interfacing with Booster would be much more useful if they were publicly available. Typically there will be several users in a lab who might need to control/monitor a given piece of hardware, not just the person who placed the PO. Making the interface public (with e.g. a GPL license) would allow us to build and distribute the python package within our lab (and the same for M-Labs' Hydra server, if they're interested) and potentially incorporate it into an ARTIQ NDSP in the future.

**Comment by ryan-summers** [comment]
Closing. Booster is now publicly available, so nothing more is required.
