### ISSUE TITLE
Enable runtime settings modification via USB

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/booster#380]
We should allow users to configure the device runtime settings via the USB interface similar to Stabilizer. This would enable the tool to be used without MQTT for initial setup.

**Comment by ryan-summers** [comment]
Although the channel tuning algorithms etc. still require MQTT, so this may have less use than Stabilizer.

CC @jordens: Do you think this is worthwhile doing for Booster, or should we leave as-is?

**Comment by jordens** [comment]
TODO: port over to stabilizer serial settings

**Comment by jordens** [comment]
#400

**Comment by ryan-summers** [comment]
@jordens This issue was actually asking about runtime settings modifications via USB, like modifying interlock settings etc. similar to how we support this on Stabilizer.

**Comment by jordens** [comment]
Doesn't that come for free now with serial settings?

**Comment by ryan-summers** [comment]
We still need to restructure the application-level logic a bit. Currently, just the `BoosterMainBoard` settings are exposed via USB, so the operator can only modify basic things like `ip`, `broker`, etc.

This was asking if we should expose channel settings etc. over USB as well. It sounds like yes.

**Comment by jordens** [comment]
Ack. Yes. Let's do it like on stabilizer, thermostat-eem, fls.
