### ISSUE TITLE
Settings are not persistent across reboots

### ISSUE THREAD

**Issue by ndnq** [quartiq/booster#399]
The issue addresses the latest as of writing this main branch 8a4d037cdce1f4500efb0d5f2314526cfda3fee5 commit.
Issue:
After setting the IP address of the device and rebooting it, all the settings stay unchanged.
How to replicate:
Pull the 8a4d037cdce1f4500efb0d5f2314526cfda3fee5 commit and build it. Flash a booster with it.
See the current settings and try updating the IP address of, for example, the broker:
(This device was used before on the v0.5.0 version of the firmware, and it correctly loaded the settings from then):

> list
...
/broker: "10.42.0.1" [default: "10.0.0.2"]
...

> set /broker "10.42.0.5"
Settings saved. Reboot device (platform reboot) to apply.

> list
...
/broker: "10.42.0.5" [default: "10.0.0.2"]
...
>platform reboot

//After rebooting

> list
...
/broker: "10.42.0.1" [default: "10.0.0.2"]
...

The same thing goes for other settings.

I tried doing the same thing with a never before flashed device. The settings were saved correctly the first time, but after the next attempt, they returned to default ones.

Reflashing it again with v0.5.0 fixes the issue, and I'm able to setup things normally.

**Comment by ryan-summers** [comment]
Indeed, I was able to reproduce this on my bench. I'm looking at a fix for this and will submit a PR shortly.

The current plan is to port over to the architecture that Stabilizer uses in the future, but I'll get a fix for the EEPROM-based settings as well in the meantime.
